# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Unicommerce'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  raw_database: "Shopify" #equivalent to project_id in BigQuery
    # Example Database name
  raw_schema: "Daton" #equivalent to dataset in BigQuery
    # Example Schema name

  currency_conversion_flag: True
  get_brandname_from_tablename_flag: True
  brandname_position_in_tablename: 0
  # Example- default_brandname: "Nike"
  default_brandname: "" 
  get_storename_from_tablename_flag: True 
  storename_position_in_tablename: 1
  # Example- default_storename: "US"
  default_storename: "" 

  UnicommerceInventory : True
  UnicommerceItemMaster : True
  UnicommercePurchaseOrders : True
  UnicommerceSaleOrders : True
  UnicommerceInvoice : True
  UnicommercePutaway : True
  UnicommerceReturnInvoice : True
  UnicommerceVendors : True
  UnicommerceVendorItemMaster : True
  UnicommerceGRN : True
  UnicommerceGatepass : True
  UnicommerceShippingPackage : True
  UnicommerceCourierReturnItemwise : True
  UnicommerceShelfwiseInventory : True

  timezone_conversion_flag : False
  raw_table_timezone_offset_hours: {
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_Invoice" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_ReturnInvoices" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_ReversePickup" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_Putaway" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_Vendors" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_VendorItemMaster" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_GRN" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_Gatepass" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_ShippingPackage" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_CourierReturnItemwise" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_ShelfwiseInventory" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_InventorySnapshot" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_ItemMaster" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_PurchaseOrders" : -7,
    "edm-saras.EDM_Daton.Brand_US_Unicommerce_BQ_SaleOrders" : -7
    }

  
# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:    
  Unicommerce:
    +schema: stg_unicommerce_dbthub
